name: hyperlocal_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Bold.ttf
        - asset: fonts/Oxygen-Light.ttf
        - asset: fonts/Oxygen-Regular.ttf
    - family: Lora
      fonts:
        - asset: fonts/Lora-Bold.ttf
        - asset: fonts/Lora-Regular.ttf
        - asset: fonts/Lora-Medium.ttf
        - asset: fonts/Lora-SemiBold.ttf